version: '3.7'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    networks:
      - strapi
 
  backend:
    build:
      context: ./back
    ports:
      - "3001:3001"
    networks:
      - strapi
  
  nginx:
    image: nginx:latest
    container_name: pa-grp-9-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt 
      - ./certbot/www:/var/www/certbot
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - strapi

    certbot: 
      image: certbot/certbot 
      container_name: certbot  
      volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email rfernando1@myges.fr -d pariscaretaker.store --agree-tos 


networks:
  strapi:
    name: Strapi
    driver: bridge
