version: '3.7'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    networks:
      - strapi
 
  backend:
    build:
      context: ./back
    ports:
      - "3001:3001"
    networks:
      - strapi
  
  nginx:
    image: nginx:latest
    container_name: pa-grp-9-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - strapi

  ngrok:
      image: ngrok/ngrok:latest
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok.yml:/etc/ngrok.yml
      ports:
        - 4040:4040
      network_mode: "host"
      depends_on:
        - nginx


networks:
  strapi:
    name: Strapi
    driver: bridge


    #//rajouter bdd + volumes 
    #// .env et creds dans le docker compose 
    #// rajouter des depends on pour verifier que le bdd est up avant le back 
