version: '3'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "80:3000" # Changed from "80:3000" to "80:80"
    networks:
      - strapi
  
  backend:
    build:
      context: ./back
    ports:
      - "3001:3001"
    networks:
      - strapi
networks:
  strapi:
    name: Strapi
    driver: bridge
