version: '3.7'

services:
  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: PCStest1
      MYSQL_USER: rafael
      MYSQL_PASSWORD: budz5subzYk&
      MYSQL_ROOT_PASSWORD: rootpassword  
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "3306:3306"
    networks:
      - strapi
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  frontend:
    image: raf211/pa:frontend
    build:
      context: ./front
    ports:
      - "3000:3000"
    networks:
      - strapi
 
  backend:
    image: raf211/pa:backend
    build:
      context: ./back
    environment: 
      - PCS_DB_NAME=PCStest1
      - PCS_DB_USER=rafael
      - PCS_DB_PASSWORD=budz5subzYk&
      - PCS_DB_HOST=db
    ports:
      - "3001:3001"
    networks:
      - strapi
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: pa-grp-9-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge

